#!/usr/bin/env tsx
/**
 * Regenerates the TypeScript definitions for the hosted Supabase schema.
 *
 * The generated file is committed. That is deliberate: the web app and the
 * ingestion service must typecheck in CI and on Vercel, where no database
 * credentials exist. Regenerating is a developer action after a migration,
 * not a build step.
 *
 *   pnpm db:types
 *
 * Requires SUPABASE_ACCESS_TOKEN (a personal access token from
 * https://supabase.com/dashboard/account/tokens). The project ref is read from
 * SUPABASE_PROJECT_REF, defaulting to the GBM Intelligence project.
 */
import { execFile } from 'node:child_process';
import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { promisify } from 'node:util';
import { config as loadDotenv } from 'dotenv';

const run = promisify(execFile);
const ROOT = resolve(import.meta.dirname, '..');

loadDotenv({ path: resolve(ROOT, '.env.local'), quiet: true });
loadDotenv({ path: resolve(ROOT, '.env'), quiet: true });

const PROJECT_REF = process.env.SUPABASE_PROJECT_REF ?? 'tyzndcjuiffnyhluddce';

const TARGETS = [
  'packages/database/src/database.types.ts',
  // The web app keeps its own copy so that apps/web installs and builds
  // standalone, without a workspace dependency Vercel would have to resolve.
  'apps/web/src/lib/database.types.ts',
];

async function main(): Promise<void> {
  if (!process.env.SUPABASE_ACCESS_TOKEN) {
    console.error(
      'Missing SUPABASE_ACCESS_TOKEN.\n' +
        'Create one at https://supabase.com/dashboard/account/tokens and add it to .env.local.\n' +
        'It is only needed to regenerate types — the build does not use it.',
    );
    process.exit(1);
  }

  console.log(`Generating types for project ${PROJECT_REF} …`);
  const { stdout } = await run(
    'npx',
    ['--yes', 'supabase@latest', 'gen', 'types', 'typescript', '--project-id', PROJECT_REF],
    { cwd: ROOT, maxBuffer: 32 * 1024 * 1024, env: process.env },
  );

  if (!stdout.includes('export type Database')) {
    throw new Error('Supabase CLI returned no schema. Check the project ref and access token.');
  }

  const header =
    '// Generated by `pnpm db:types` from the hosted Supabase schema.\n' +
    '// Do not edit by hand — regenerate after applying a migration.\n\n';

  for (const target of TARGETS) {
    await writeFile(resolve(ROOT, target), header + stdout, 'utf8');
    console.log(`  wrote ${target}`);
  }
}

main().catch((err: unknown) => {
  console.error(err instanceof Error ? err.message : String(err));
  process.exit(1);
});
